### ISSUE TITLE
No field mGradientRadius in class Landroid/graphics/drawable/GradientDrawable$GradientState;

### ISSUE THREAD

**Issue by BarretWu** [duanhong169/DrawableToolbox#9]
W: Accessing hidden field Landroid/graphics/drawable/GradientDrawable$GradientState;->mGradientRadius:F (dark greylist, reflection)
W: java.lang.NoSuchFieldException: No field mGradientRadius in class Landroid/graphics/drawable/GradientDrawable$GradientState; (declaration of 'android.graphics.drawable.GradientDrawable$GradientState' appears in /system/framework/framework.jar)
W:     at java.lang.Class.getDeclaredField(Native Method)
W:     at top.defaults.drawabletoolbox.a.a(Compatible.kt:33)
W:     at top.defaults.drawabletoolbox.a.a(Compatible.kt:147)
W:     at top.defaults.drawabletoolbox.DrawableBuilder.a(DrawableBuilder.kt:307)
W:     at top.defaults.drawabletoolbox.DrawableBuilder.a(DrawableBuilder.kt:187)
W:     at b.b.a.a.b.a(DrawableUtil.kt:87)
W:     at com.wwyy.wzhxl.ui.main.recommend.AdapterRecommend.a(AdapterRecommend.kt:999)
W:     at com.wwyy.wzhxl.ui.main.recommend.AdapterRecommend.b(AdapterRecommend.kt:804)
W:     at com.zjw.des.base.BaseAdapter.a(BaseAdapter.kt:51)
W:     at com.zjw.des.base.BaseAdapter.onBindViewHolder(BaseAdapter.kt:41)
W:     at com.zjw.des.base.BaseAdapter.onBindViewHolder(BaseAdapter.kt:10)
W:     at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
W:     at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
W:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
W:     at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
W:     at androidx.recyclerview.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:288)
W:     at androidx.recyclerview.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:345)
W:     at androidx.recyclerview.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:361)
W:     at androidx.recyclerview.widget.GapWorker.prefetch(GapWorker.java:368)
W:     at androidx.recyclerview.widget.GapWorker.run(GapWorker.java:399)
W:     at android.os.Handler.handleCallback(Handler.java:873)
W:     at android.os.Handler.dispatchMessage(Handler.java:99)
W:     at android.os.Looper.loop(Looper.java:226)
W:     at android.app.ActivityThread.main(ActivityThread.java:7225)
W:     at java.lang.reflect.Method.invoke(Native Method)
W:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:962)

**Comment by BlueCobold** [comment]
Any comment on this? I'm using quite a few gradients and my logcat is being spammed with that.
